name = "pilah-sampah-yuk-multiplayer"
main = "worker/index.js"
compatibility_date = "2026-07-16"

[assets]
directory = "./game-pilah-sampah"
binding = "ASSETS"
run_worker_first = true

[[durable_objects.bindings]]
name = "GAME_HUB"
class_name = "GameHub"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameHub"]
